name: flutter_slide_swap
description: Flutter widget that swaps children with each other in slide animation.
version: 1.1.2
homepage: https://github.com/zuvola/flutter_slide_swap

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
