name: flutter_slide_swap
description: Flutter widget that swaps children with each other in slide animation.
version: 1.3.0
homepage: https://github.com/zuvola/flutter_slide_swap

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
